// Generated by CoffeeScript 1.6.3
(function() {
  window.TextSizer = (function() {
    TextSizer.default_options = {
      sizes: [
        {
          max: 19,
          min: 10,
          className: "size_0"
        }, {
          max: 99999,
          min: 20,
          className: "size_max"
        }, {
          max: 9,
          min: 0,
          className: "size_min"
        }
      ]
    };

    function TextSizer(elements, options) {
      if (options == null) {
        options = null;
      }
      if (options === null) {
        options = TextSizer.default_options;
      }
      this.options = options;
      this.sizes = options['sizes'];
      this.elements = elements;
    }

    TextSizer.prototype.assignClass = function() {
      var _this = this;
      return this.elements.each(function(i, el) {
        var data_size, max, size, text_size, _i, _len, _ref;
        el = $(el);
        text_size = el.text().length;
        max = _this.sizes[_this.sizes.length - 1];
        _ref = _this.sizes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          size = _ref[_i];
          if (size.max >= text_size && size.min <= text_size) {
            max = size;
          }
        }
        data_size = el.attr('data-size');
        if (!$.isEmptyObject(data_size)) {
          el.removeClass(data_size);
        }
        el.attr('data-size', max.className);
        return el.addClass(max.className);
      });
    };

    return TextSizer;

  })();

}).call(this);
